apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    type: gotest
  name: gotest
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    type: gotest
  sessionAffinity: None
  type: ClusterIP
